name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

# REQUIRED for OIDC authentication to AWS
permissions:
  id-token: write
  contents: read

jobs:
  # JOB 1: Security Scan
  python-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install bandit
      - run: bandit -r app/ -s B104

  # JOB 2: Build and Push Container
  build-and-push:
    needs: python-security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -f docker/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/football-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/football-app:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/football-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/football-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/football-app:latest

  # JOB 3: THE ONE-CLICK DEPLOY (Using your OIDC Role)
  provision-and-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Make sure the GitHub runner has Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      # SECURE AWS LOGIN using your existing Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }} # e.g., arn:aws:iam::123456789:role/github-actions-terraform-role
          aws-region: us-east-1

      # 1. Provision Infrastructure
      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init -upgrade
          terraform apply -auto-approve

      # 2. Connect to Cluster
      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name flask-devsecops-dev-eks --region us-east-1

      # 3. Inject API Key & Deploy App (# Create secret with all three variables from GitHub)
      - name: K8s Deploy
        run: |
          kubectl create secret generic football-app-secrets \
            --from-literal=FOOTBALL_API_KEY="${{ secrets.FOOTBALL_API_KEY }}" \
            --from-literal=FOOTBALL_API_BASE_URL="${{ secrets.FOOTBALL_API_BASE_URL }}" \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl apply -f k8s/manifests/