name: Deploy EKS Infrastructure

# 1. Naming and Triggers
on:
    # push:
    #    branches: [ "main", "feature/terraform-eks-infra" ]
        # This allows you to click a button in github to run it manually
    workflow_dispatch:
        inputs:
            action:
                description: 'terraform Action (plan or apply)'
                required: true
                default: 'plan'
                type: choice
                options:
                    - plan
                    - apply

# 2. Security & Permissions - The OIDC Passwordless AWS login
permissions:
    id-token: write # This gives the GitHub runner permissions to generate the digital signature to hand to AWS.
    contents: read  # Standard permission allowing the runner to download your repository code.

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -reconfigure -upgrade


      - name: Terraform Plan
      # Add the secret here so 'Plan' doesn't fail due to a missing variable
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform
          terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Destroy
      # You should also add it here just in case Terraform needs to refresh the resource before deleting
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: |
          cd terraform
          terraform destroy -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: |
          cd terraform
          terraform destroy -auto-approve