name: "2. Infrastructure Add-ons"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (plan, apply, destroy)'
        required: true
        default: 'plan'
        type: choice
        options: [plan, apply, destroy]

permissions:
  id-token: write
  contents: read

jobs:
  addons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Add-ons Logic
        env:
          TF_VAR_alb_handshake_secret: ${{ secrets.ALB_HANDSHAKE_SECRET }}
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform-addons
          terraform init -reconfigure -upgrade
          if [ "${{ github.event.inputs.action }}" == "plan" ]; then
            terraform plan -input=false
          elif [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve -input=false
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            
            terraform destroy -auto-approve -input=false
          fi
