name: Deploy EKS Infrastructure

# 1. Naming and Triggers
on:
    # push:
    #    branches: [ "main", "feature/terraform-eks-infra" ]
        # This allows you to click a button in github to run it manually
    workflow_dispatch:
        inputs:
            action:
                description: 'Terraform Action (plan, apply or destroy)'
                required: true
                default: 'plan'
                type: choice
                options:
                    - plan
                    - apply
                    - destroy

# 2. Security & Permissions - The OIDC Passwordless AWS login
permissions:
    id-token: write # This gives the GitHub runner permissions to generate the digital signature to hand to AWS.
    contents: read  # Standard permission allowing the runner to download your repository code.

jobs:
  terraform-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      # ==========================================
      # LAYER 1: CORE (Networking & EKS)
      # ==========================================

      - name: Terraform Init (CORE)
        run: |
          cd terraform-core
          terraform init -reconfigure -upgrade


      - name: Terraform Plan (CORE)
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        run: 
          cd terraform-core
          terraform plan

      - name: Terraform Apply (CORE)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: |
          cd terraform-core
          terraform apply -auto-approve

      # ==========================================
      # LAYER 2: ADD-ONS (Monitoring & Ingress)
      # ==========================================

      - name: Terraform Init (ADD-ONS)
# We only init if we are planning or applying (Destroy has its own init later)
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        run: |
          cd terraform-addons
          terraform init -reconfigure -upgrade

      - name: Terraform Plan (ADD-ONS)
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform-addons
          terraform plan

      - name: Terraform Apply (ADD-ONS)
        if: github.event.inputs.action == 'apply'
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform-addons
          terraform apply -auto-approve

      # ==========================================
      # CLEANUP: DESTROY LOGIC
      # ==========================================

      - name: Terraform Destroy (ADD-ONS)
        if: github.event.inputs.action == 'destroy'
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform-addons
          terraform init -reconfigure -upgrade
          terraform destroy -auto-approve

      - name: Terraform Destroy (CORE)
        if: github.event.inputs.action == 'destroy'
        run: |
          cd terraform-core
          terraform destroy -auto-approve